source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'Stone Store Star' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stone Store Star
  pod 'Alamofire', '~> 4.5'
  pod 'RealmSwift'
  pod 'AlamofireImage'

  target 'Stone Store StarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Stone Store StarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
