# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'desafio-mobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for desafio-mobile
  pod ‘Alamofire’
  pod ‘ObjectMapper’
  pod ‘SDWebImage’

  target 'desafio-mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'desafio-mobileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
